### ISSUE TITLE
Light cone projection fails when weight_field is given.

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt_astro_analysis#36]
Light cone projections fails when a weight_field is provided, as in the following example:
```
import yt
from yt.extensions.astro_analysis.cosmological_observation.api import \
     LightCone

lc = LightCone('enzo_tiny_cosmology/32Mpc_32.enzo',
               'Enzo', 0., 0.1, observer_redshift=0.0, time_data=False)
lc.calculate_light_cone_solution(seed=123456789, filename="LC/solution.txt")
lc.project_light_cone((600.0, "arcmin"), (60.0, "arcsec"), 'temperature',
                      weight_field='density', save_stack=True, save_final_image=True,
                      save_slice_images=True, njobs=-1)
```

This gives the following error:
```
Traceback (most recent call last):
  File "light_cone_projection.py", line 30, in <module>
    njobs=-1)
  File "/Users/britton/Documents/work/yt/yt/yt/analysis_modules/cosmological_observation/light_cone/light_cone.py", line 343, in project_light_cone
    frb["weight_field"]),
  File "/Users/britton/Documents/work/yt/yt/yt/visualization/fixed_resolution.py", line 134, in __getitem__
    int(self.antialias))
  File "/Users/britton/Documents/work/yt/yt/yt/geometry/coordinates/cartesian_coordinates.py", line 158, in pixelize
    antialias, dimension, periodic)
  File "/Users/britton/Documents/work/yt/yt/yt/geometry/coordinates/cartesian_coordinates.py", line 225, in _ortho_pixelize
    finfo = self.ds._get_field_info(field)
  File "/Users/britton/Documents/work/yt/yt/yt/data_objects/static_output.py", line 798, in _get_field_info
    raise YTFieldNotFound((ftype, fname), self)
yt.utilities.exceptions.YTFieldNotFound: Could not find field '('all', 'weight_field')' in RD0000.
```

**Comment by brittonsmith** [comment]
Fixed in PR #37.
